#!/bin/bash
echo "tests.cpp -> tests.o"
g++ -c -Wall -Werror -fpic tests.cpp

echo "tests.o -> libtests.so"
g++ -shared -o libtests.so tests.o


#added -lstdc++fs for filesystem support
echo "compiling main tests"
g++ -O2 -Wall -o test maintest.cpp -ldl -lstdc++fs

echo "running programm:
"
./test