#!/bin/bash
echo "tests.cpp -> tests.o"
x86_64-w64-mingw32-g++ -c -Wall -Werror -fpic tests.cpp

echo "tests.o -> libtests.so"
x86_64-w64-mingw32-g++ -shared -o libtests.dll tests.o


#added -lstdc++fs for filesystem support
echo "compiling main tests"
x86_64-w64-mingw32-g++ -O2 -Wall -o test maintest.cpp -ldl -lstdc++fs

echo "running programm:
"
./test